### ISSUE TITLE
Charge Limit not preserved after reboot

### ISSUE THREAD

**Issue by stefanhoelzl** [FrameworkComputer/framework-system#25]
When using `framework_tool` to set a charge limit it is not preserved after reboot.
After rebooting the charge limit is always 100%.

I am running it on a Framework 13 AMD and Fedora 39 Silverblue with [these kernel patches](https://lore.kernel.org/chrome-platform/20231005160701.19987-1-dustin@howett.net/)

**Comment by DeflateAwning** [comment]
As a temporary workaround until an option to save the configuration is added, I added the following to my `/etc/rc.local` file:

```bash
cat /etc/rc.local
#!/bin/sh -e

# By default this script does nothing.

# Set the Framework charge limit to 90%
/usr/local/bin/framework_tool --charge-limit 90

exit 0
```

This works on Linux Mint, at least.

**Comment by JohnAZoidberg** [comment]
I debugged this and the reason is that the BIOS overwrites your setting on every boot.
You can go into the BIOS settings to make it persistent.

We're investigating how to best fix this.

**Comment by xamindar** [comment]
It needs to write its update to the bios value. Any other route is just a workaround to this bug.

**Comment by leiserfg** [comment]
I feel it's a https://xkcd.com/1172/ case, cause I like that it sets the value only temporarily, so I can set the limit to 80% in the BIOS and upgrade it to 100% only when I'm in a long travel. So if changed, please make it so writing to BIOS is only optional.

**Comment by leiserfg** [comment]
I'm using:
```toml
[Unit]
After=multi-user.target
Description=Set battery charge limit

[Service]
ExecStart=/usr/bin/env bash -c 'echo 80 > /sys/class/power_supply/BAT1/charge_control_end_threshold'
RemainAfterExit=true
Type=oneshot

[Install]
WantedBy=multi-user.target

```
